### PR TITLE
Add prettier-fix script to fix all repository

### PR DESCRIPTION
**Pull request by lolgab**
Run prettier-fix on all files

### CODE REVIEW

**Comment by lolgab** [comment]
[Codacy](https://codacy.com) was giving a lot of prettier warnings.
I run here `prettier --write .` to fix them.

**Comment by nathan815** [comment]
Thank you for assisting! This problem actually happened in another branch, after I had run eslint and prettier on the code.

But it may be working now.

**Comment by lolgab** [comment]
I checked on the master branch and I can't more find the prettier issues.
Can you confirm?

**Comment by nathan815** [comment]
@lolgab Unfortunately I am having trouble getting Codacy to run again on this repo. I had uninstalled the app previously, and just reinstalled it. It doesn't seem to be picking up the new commits or PRs now (codacy.com is showing an [old state of the repo](https://app.codacy.com/gh/seeus-dev/seeus-app/pullRequests)).

**Comment by lolgab** [comment]
You can enable analysis on a branch by going to `Settings` -> `Branches`

**Comment by nathan815** [comment]
Alright, I think it's all good now. Thank you for the help.

**Comment by lolgab** [comment]
Thank you very much!
If you think prettier pattern in Codacy works as expected, would you mind to comment on the Codacy issue?
Thank you

**Pull request closed without merging**
